// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hashes.sql

package db

import (
	"context"
)

const createHash = `-- name: CreateHash :one
INSERT INTO hashes (address, anchor_time, song_id) VALUES (?, ?, ?) RETURNING address, anchor_time, song_id
`

type CreateHashParams struct {
	Address    int64
	AnchorTime int64
	SongID     int64
}

func (q *Queries) CreateHash(ctx context.Context, arg CreateHashParams) (Hash, error) {
	row := q.db.QueryRowContext(ctx, createHash, arg.Address, arg.AnchorTime, arg.SongID)
	var i Hash
	err := row.Scan(&i.Address, &i.AnchorTime, &i.SongID)
	return i, err
}

const getHashByAddress = `-- name: GetHashByAddress :many
SELECT address, anchor_time, song_id FROM hashes WHERE address = ?
`

func (q *Queries) GetHashByAddress(ctx context.Context, address int64) ([]Hash, error) {
	rows, err := q.db.QueryContext(ctx, getHashByAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hash
	for rows.Next() {
		var i Hash
		if err := rows.Scan(&i.Address, &i.AnchorTime, &i.SongID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
