// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Hash struct {
	Address    int64
	AnchorTime int64
	SongID     int64
}

type Song struct {
	ID    int64
	Title string
	Path  string
}
