// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: songs.sql

package db

import (
	"context"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (title, path) VALUES (?, ?) RETURNING id, title, path
`

type CreateSongParams struct {
	Title string
	Path  string
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong, arg.Title, arg.Path)
	var i Song
	err := row.Scan(&i.ID, &i.Title, &i.Path)
	return i, err
}

const getSong = `-- name: GetSong :one
SELECT id, title, path FROM songs WHERE id = ?
`

func (q *Queries) GetSong(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSong, id)
	var i Song
	err := row.Scan(&i.ID, &i.Title, &i.Path)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, path FROM songs ORDER BY id
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(&i.ID, &i.Title, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
